DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS machine;

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL,
  privilege INTEGER NOT NULL
);

CREATE TABLE machine (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  ip TEXT UNIQUE NOT NULL,
  host TEXT NOT NULL,
  cpu TEXT NOT NULL,
  mem TEXT NOT NULL,
  owner_id INTEGER NOT NULL,
  update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  update_user INTEGER DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (owner_id) REFERENCES user (id),
  FOREIGN KEY (update_user) REFERENCES user (id)
);

INSERT INTO user (username, password, privilege) VALUES ("admin", "admin", 0)
